### PR TITLE
Add documentation and navigation tooltips

### PR DESCRIPTION
**Pull request by krimsonkla**
@shalupov One of the things I was looking forward to in your plugin was integrated documentation. Here is a first stab at adding CFN documentation.

I'm not a java developer so forgive me if there are major mistakes and please provide feedback.

### CODE REVIEW

**Comment by krimsonkla** [comment]
Displays navigation tool tip showing the node you would navigate to when holding CTRL and hovering over Refs.
Displays full resource documentation when pressing CTRL-Q on a resource Type property and property documentation when pressing CTRL-Q on a resource property

**Comment by shalupov** [comment]
Thanks! One question - how "Place plugin into plugin folder for easier debugging" helps with debugging?

**Comment by krimsonkla** [comment]
When I would launch the app via runIdeaWithPlugin, the plugin was not placed into the plugin folder. I would have to launch, load the plugin from the file system, then restart the debug session. Perhaps there is a better way?

**Comment by shalupov** [comment]
Yes, it should work with "plugin.path" system property (see https://github.com/krimsonkla/idea-cloudformation/blob/master/build.gradle#L115). And it definitely works for me.

**Comment by krimsonkla** [comment]
Ill revert that change out and test a bit.

**Comment by shalupov** [comment]
I've merged two other commits. Thanks!

**Comment by shalupov** [comment]
Merged "Place plugin into plugin folder for easier debugging" too. For some unknown reason "plugin.path" loses classes from zip for me.

**Comment by krimsonkla** [comment]
(Y)

**Pull request closed without merging**
